// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/sensors": {
            "get": {
                "description": "Get list of all sensors",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Get all sensors",
                "responses": {
                    "200": {"description": "OK"},
                    "500": {"description": "Internal Server Error"}
                }
            },
            "post": {
                "description": "Create a new sensor",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Create sensor",
                "parameters": [{"description": "Sensor data", "name": "sensor", "in": "body", "required": true, "schema": {}}],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v1/sensors/{id}": {
            "get": {
                "description": "Get sensor details by ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Get sensor by ID",
                "parameters": [{"type": "integer", "description": "Sensor ID", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "404": {"description": "Not Found"}
                }
            },
            "put": {
                "description": "Update an existing sensor",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Update sensor",
                "parameters": [
                    {"type": "integer", "description": "Sensor ID", "name": "id", "in": "path", "required": true},
                    {"description": "Sensor update data", "name": "sensor", "in": "body", "required": true, "schema": {}}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            },
            "delete": {
                "description": "Delete a sensor by ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Delete sensor",
                "parameters": [{"type": "integer", "description": "Sensor ID", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v1/sensors/{id}/value": {
            "patch": {
                "description": "Update value and status of a sensor",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Update sensor value",
                "parameters": [
                    {"type": "integer", "description": "Sensor ID", "name": "id", "in": "path", "required": true},
                    {"description": "Value and status", "name": "value", "in": "body", "required": true, "schema": {}}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v1/sensors/temperature/{location}": {
            "get": {
                "description": "Get temperature data for a specific location",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["sensors"],
                "summary": "Get temperature by location",
                "parameters": [{"type": "string", "description": "Location", "name": "location", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v2/users/register": {
            "post": {
                "description": "Create a new user account",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Register new user",
                "parameters": [{"description": "User registration data", "name": "user", "in": "body", "required": true, "schema": {"type": "object", "properties": {"email": {"type": "string"}, "password": {"type": "string"}, "name": {"type": "string"}}}}],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v2/users/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "User login",
                "parameters": [{"description": "Login credentials", "name": "credentials", "in": "body", "required": true, "schema": {"type": "object", "properties": {"email": {"type": "string"}, "password": {"type": "string"}}}}],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/v2/devices": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all devices for authenticated user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["devices"],
                "summary": "Get user devices",
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"},
                    "500": {"description": "Internal Server Error"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create a new device for authenticated user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["devices"],
                "summary": "Create new device",
                "parameters": [{"description": "Device data", "name": "device", "in": "body", "required": true, "schema": {"type": "object", "properties": {"name": {"type": "string"}, "device_type": {"type": "string"}}}}],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        },
        "/api/v2/devices/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Delete a device by ID",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["devices"],
                "summary": "Delete device",
                "parameters": [{"type": "string", "description": "Device ID", "name": "id", "in": "path", "required": true}],
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"},
                    "404": {"description": "Not Found"},
                    "500": {"description": "Internal Server Error"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SmartHome API",
	Description:      "SmartHome Platform API - управление умным домом",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
